### ISSUE TITLE
admin password expires

### ISSUE THREAD

**Issue by rakesh-roshan** [xetus-oss/docker-archiva#1]
How to disable password expiry?

**Comment by tkent** [comment]
@rakesh-roshan 

This is a little more of a "how do I configure archiva" question than something about our container configuration. In the future, please direct such questions over to the [archiva mailing lists](http://archiva.apache.org/mail-lists.html) or stackoverflow.

The setting for password expiration is documented [here on the archiva site](http://archiva.apache.org/docs/2.2.1/adminguide/customising-security.html). The file they mention the docs, `conf/security.properties`, can be modified separately from the container in the data volume under the `conf` directory.

One last thing - if the password is already expired for a user and you don't have a way of reseting it from the UI, then you'll want to manually change the JDOUSER table in the associated database to get access.

**Comment by rakesh-roshan** [comment]
Thanks, Yeah I found the archiva.xml file. Mainly I wanted to know the location of conf file in container.
