### ISSUE TITLE
Running from example seems to hang on "Loading"

### ISSUE THREAD

**Issue by Dragas** [xetus-oss/docker-archiva#11]
After changing default ports from 8080 to 7777 and 8443 to 8888, and then using respective `-p 7777:8080 -p 8888:8443` calls, it seems to hang on a "loading" statement without doing anything else. Are you sure there aren't any additional steps that I need to take to get it up and running?

Neither request log nor archiva log seem to expose any exceptions when making a request to `ip:7777/` page via HTTP protocol.

**Comment by x-lhan** [comment]
That is the only configuration needs for mapping http/https(For https support also need to add `-e SSL_ENABLED=true`) port. Sometime the initial setup may not finish cause some client js code not loading properly which seems like what you describe(hang on a "loading" page). A refresh on the page will solve the problem.

**Comment by Dragas** [comment]
Aye. Switching browsers (mac latest firefox to latest chrome) helped.
