### ISSUE TITLE
What is the root password for Archiva Docker image?

### ISSUE THREAD

**Issue by dungba88** [xetus-oss/docker-archiva#14]
Hi

I wanted to install an editor (vim/nano) to change the configuration (disable the password expiration), but `sudo` is not installed. Also `su` required a password. Please tell me what the password is.

**Comment by tkent** [comment]
@dungba88 

Your question actually doesn't have anything to do with our image or archiva - in general, docker images shouldn't execute tasks as the root user or have sudo/su installed. So, what you're seeing is expected.

To your specific question, there is no root password. If you'd like to execute commands as the root user, use the docker `exec` command specifying the `--user` flag as `root`. (See https://docs.docker.com/engine/reference/commandline/exec/)

However, you probably shouldn't be editing configuration files in this image by hand. If you need to configure something differently in the image you should either...

1. Create a custom image, using this image as a base image
2. Overwrite the configuration file you want to modify using a custom volume mount
3. If the file you're changing is the Jetty configuration you can use the documented `JETTY_CONFIG_PATH`
