### ISSUE TITLE
Hello, I'm new to docker. How easy would it be to add the $PORT env variable as a configuration parameter ? Thanks

### ISSUE THREAD

**Issue by apostolou** [xetus-oss/docker-archiva#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tkent** [comment]
Hey @apostolou - Unfortunately, that question doesn't quite make sense without more context. If you're looking to modify the port that the container exposes on the host, then you can pretty easily do that using standard docker port mapping (the `-p` flag on the command line).
