### ISSUE TITLE
Container does not start as expected (HTTP ERROR 404)

### ISSUE THREAD

**Issue by Krysztokowski** [xetus-oss/docker-archiva#27]
**Describe the bug**
I expected a web UI after the container start.

**To Reproduce**
1. docker pull xetusoss/archiva
2. docker run --name archiva -p 8080:8080 xetusoss/archiva
3. See error in browser:

HTTP ERROR 404
Problem accessing /auth/. Reason:

Not Found
Powered by Jetty://

**Environment Details**
Docker Version: 19.03.8
Host OS: Ubuntu 20.04.1 LTS

**Comment by tkent** [comment]
:wave: @Krysztokowski 

From the error you included, it seems you're trying to reach an invalid path `/auth`. The fact that you're getting a 404 error indicates that the container is started, so I don't think there is any problem here.

Why don't you try to load http://localhost:8080 and see what happens.

**Comment by Krysztokowski** [comment]
Got it - well.. I tried to load [http://localhost:8080](http://localhost:8080) with chrome but I got a redirect to [http://localhost:8080/auth/](http://localhost:8080/auth/). I tried it in incognito mode again and it worked. Looks like my browser cache creates trouble (had an keycloak instance on port 8080 before). Now it works fine, thanks! (=
