### ISSUE TITLE
How to set rest.baseUrl if behind proxy. 

### ISSUE THREAD

**Issue by ahmednawazkhan** [xetus-oss/docker-archiva#28]
Hi. I am new to archiva. I just want to set `rest.baseUrl` in archiva configuration. the only file i saw this option was in `/archiva-data/conf/archiva.xml` but i have noticed that this file is being recreated each time new container is created. My question is how does the container works. how are these configurations created at runtime. what is `jetty.xml` and where can I set `rest.baseUrl` to be a permanent change. Thanks.

**Comment by tkent** [comment]
👋  

Just set the environment variable `PROXY_BASE_URL` ([see here](https://github.com/xetus-oss/docker-archiva/blob/92155821ba097a19f4911a0ec2128ae035ea90bc/files/entrypoint.sh#L123))

**Comment by ahmednawazkhan** [comment]
Thank you. that did the trick
