### ISSUE TITLE
Dockerhub tag `latest` does not seem to get updated 

### ISSUE THREAD

**Issue by neumantm** [xetus-oss/docker-archiva#33]
**Describe the bug**
When looking at https://hub.docker.com/r/xetusoss/archiva/tags it seems that the `latest` tag was not updated the last 7 months.
When deploying it, archiva says it is version 2.2.5

**Comment by tkent** [comment]
👋 @neumantm  - ah, you're right. Thanks for the report!

It seems `develop`, but not `latest` was being updated. That's been fixed!
