### ISSUE TITLE
Adding port 8443 to port list

### ISSUE THREAD

**Issue by wiscwork** [xetus-oss/docker-archiva#39]
I am trying to get Archiva to run with ssl. I have a working stand alone Archive running but thcontinerized version if blocking port 8443. It looks like the docker-compose.yaml is missing a definition for this port. I can share the wrapper.conf, jetty.conf, and jetty-ssl.conf files with you in return for help on this issue.

**Comment by tkent** [comment]
:wave: @wiscwork - Welcome! A few things on this issue.

1. The `docker-compose.yaml` included in this project is for building, testing, and demonstration. You'll want to write your own if you are hosting things yourself in a docker server (and there is a [not-really-maintained helm chart](https://github.com/xetus-oss/helm-charts/tree/master/xetusoss-archiva) if you are running in k8s)
2. It is not recommended to provide TLS through Jetty and it's not something we provide examples of. There is a helpful example in this project [of using nginx to provide TLS](https://github.com/xetus-oss/docker-archiva/blob/master/docker-compose.nginx-https.yaml), which is a much less painful path.
